// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WellworkGS.Data;

#nullable disable

namespace WellworkGS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.AlertaCrise", b =>
                {
                    b.Property<int>("IdAlertaCrise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDALERTACRISE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlertaCrise"));

                    b.Property<DateTime>("DataHoraAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATAHORA_ALERTA");

                    b.Property<int>("IdGestor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDGESTOR");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDUSUARIO");

                    b.Property<string>("StatusAlerta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_ALERTA");

                    b.HasKey("IdAlertaCrise");

                    b.HasIndex("IdGestor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ALERTACRISE", (string)null);
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.Gestor", b =>
                {
                    b.Property<int>("IdGestor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("idGestor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGestor"));

                    b.Property<string>("CargoGestor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("cargo_gestor");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("EmailGestor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("email_gestor");

                    b.Property<string>("NomeGestor")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("nome_gestor");

                    b.Property<string>("SenhaGestor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("senha_gestor");

                    b.HasKey("IdGestor");

                    b.HasIndex("EmailGestor")
                        .IsUnique();

                    b.ToTable("Gestor", (string)null);
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.Lembrete", b =>
                {
                    b.Property<int>("IdLembrete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDLEMBRETE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLembrete"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ATIVO");

                    b.Property<int?>("Frequencia")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FREQUENCIA");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDUSUARIO");

                    b.Property<string>("TipoLembrete")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_LEMBRETE");

                    b.HasKey("IdLembrete");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LEMBRETE", (string)null);
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.Meta", b =>
                {
                    b.Property<int>("IdMeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDMETA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMeta"));

                    b.Property<string>("DescricaoMeta")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("NVARCHAR2(90)")
                        .HasColumnName("DESCRICAO_META");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDUSUARIO");

                    b.Property<string>("TituloMeta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TITULO_META");

                    b.HasKey("IdMeta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("META", (string)null);
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.Tarefa", b =>
                {
                    b.Property<int>("IdTarefa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDTAREFA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarefa"));

                    b.Property<DateTime?>("DataHoraTarefa")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATAHORA_TAREFA");

                    b.Property<string>("DescricaoTarefa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DESCRICAO_TAREFA");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDUSUARIO");

                    b.Property<string>("StatusTarefa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_TAREFA");

                    b.Property<string>("TituloTarefa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TITULO_TAREFA");

                    b.HasKey("IdTarefa");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TAREFA", (string)null);
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.Temporizador", b =>
                {
                    b.Property<int>("IdTemporizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDTIMER");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTemporizador"));

                    b.Property<int?>("Duracao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DURACAO");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FIM");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDUSUARIO");

                    b.Property<DateTime?>("Inicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INICIO");

                    b.Property<string>("StatusTemporizador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_TIMER");

                    b.Property<string>("TipoTemporizador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO_TIMER");

                    b.HasKey("IdTemporizador");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TIMER", (string)null);
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("idUsuario");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Acessibilidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("acessibilidade");

                    b.Property<string>("CargoUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("cargo_usuario");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("email_usuario");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("nome_usuario");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("senha_usuario");

                    b.HasKey("IdUsuario");

                    b.HasIndex("EmailUsuario")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.AlertaCrise", b =>
                {
                    b.HasOne("WellworkGS.Infra.Persistence.Models.Gestor", "Gestor")
                        .WithMany("AlertasDeCrise")
                        .HasForeignKey("IdGestor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WellworkGS.Infra.Persistence.Models.Usuario", "Usuario")
                        .WithMany("AlertasDeCrise")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gestor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.Lembrete", b =>
                {
                    b.HasOne("WellworkGS.Infra.Persistence.Models.Usuario", "Usuario")
                        .WithMany("Lembretes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.Meta", b =>
                {
                    b.HasOne("WellworkGS.Infra.Persistence.Models.Usuario", "Usuario")
                        .WithMany("Metas")
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.Tarefa", b =>
                {
                    b.HasOne("WellworkGS.Infra.Persistence.Models.Usuario", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.Temporizador", b =>
                {
                    b.HasOne("WellworkGS.Infra.Persistence.Models.Usuario", "Usuario")
                        .WithMany("Temporizadores")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.Gestor", b =>
                {
                    b.Navigation("AlertasDeCrise");
                });

            modelBuilder.Entity("WellworkGS.Infra.Persistence.Models.Usuario", b =>
                {
                    b.Navigation("AlertasDeCrise");

                    b.Navigation("Lembretes");

                    b.Navigation("Metas");

                    b.Navigation("Tarefas");

                    b.Navigation("Temporizadores");
                });
#pragma warning restore 612, 618
        }
    }
}
